Rename receive event data property
jfrog/jfrog-ide-webview pull request #26
Opened 2023-07-16 14:44 UTC by Or-Geva

To ensure consistent handling of various message types, the receiver events in the web view have been refactored to follow a standardized JSON structure:

```json
{
"type": "<value>",
"data": "<value>"
}
```
 This allows for easier handling of different event notifications received by the web view.

2023-07-31 13:09 UTC, yahavi requested changes

2023-07-31 13:09 UTC, yahavi commented on README.md
>  window.postMessage({
The three JSONs in the README are not aligned properly. Let's fix the indentation to make them easy to read.

2023-07-31 13:09 UTC, yahavi commented on src/App.test.tsx
> +		const mock = {
"mock" is very abstract. Please be more specific when naming variables.
```suggestion
		const mockPage = {
```
(Let's do this change in all other locations)

2023-07-31 13:09 UTC, yahavi commented on src/components/UI/Modal/pages/LoginModal.tsx
>  					<div />
Is the empty div by purpose?

2023-08-02 10:01 UTC, Or-Geva commented on src/components/UI/Modal/pages/LoginModal.tsx
>  					<div />
Yes, to separate sentences

2023-08-03 13:41 UTC, merged